### ISSUE TITLE
El campo DNI tiene flechas up/dwn

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-covid/planificacion#83]
# :beetle: Problema detectado

Cuando uno se posiciona sobre el campo de Número de Documento aparecen las flechas de incrementar/decrementar que pueden confundir al usuario e incluso sin querer tocarlas y modificar el número tipeado

![image](https://user-images.githubusercontent.com/39915206/108522269-6a1a1380-72ab-11eb-9e06-f84a936666e1.png)

# :notebook: Acciones sugeridas

- Quitar esa opción

**Comment by faloi** [comment]
Encontré este hack para ocultar las flechitas sin que deje de ser input number:

```css
/* Specilly used for Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
 /* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}
```
